#!/bin/sh

ONOFF=$1
SXLEDPROC=/proc/silex/led
LEDS="1 2 3 4 5 6 7 8 9"

show_help() {
	echo "Usage: $0 {on|off}"
}

if [ "${ONOFF}" != 'on' ] && [ "${ONOFF}" != 'off' ]; then
	show_help
	exit 1
fi

cd "${SXLEDPROC}"
for LED in ${LEDS} ; do
	case "${ONOFF}" in
		'on') echo "0 1 1 3 0 0 0" > "${LED}" ;;
		'off') echo "0 0 1 3 0 0 0" > "${LED}" ;;
	esac
done

